### ISSUE TITLE
Create DB

### ISSUE THREAD

**Issue by BrandonWalker88** [BrandonWalker88/gamers_alike#2]
Create the DB

**Comment by MBPJason** [comment]
Made a table that acts as the method to send friend invites, for it to get accepted, the ability to get outgoing and incoming requests, and grab a full friends list based on them passing the accepted criteria.

**Comment by MBPJason** [comment]
Made a table that acts as the method to send user invites to play games using their current game as a criteria. It has the ability to sort on outgoing invites, incoming invites, accept or deny voice chat. We should fire a delete when an invite is accepted and setup a timer to destroy it automatically when it hasn't been responded to in a certain amount of time.
